steps:

- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=staging.env.enc
  - --plaintext-file=.env
  - --location=global
  - --keyring=linksight
  - --key=linksight

- name: 'gcr.io/cloud-builders/npm'
  dir: 'app'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  dir: 'app'
  args: ['run', 'build']
  env:
    - PUBLIC_URL=https://linksight.thinkingmachin.es
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/linksight', '.']
images: ['gcr.io/$PROJECT_ID/linksight']
