# Generated by Django 2.0.7 on 2018-07-03 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180703_0440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchitem',
            options={'ordering': ['dataset_index', '-total_score']},
        ),
    ]
