# Generated by Django 2.0.7 on 2018-08-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_match_matched_dataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchitem',
            name='matched_barangay_psgc_code',
        ),
        migrations.RemoveField(
            model_name='matchitem',
            name='matched_city_municipality_psgc_code',
        ),
        migrations.RemoveField(
            model_name='matchitem',
            name='matched_province_psgc_code',
        ),
        migrations.AddField(
            model_name='matchitem',
            name='matched_barangay_psgc',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='matchitem',
            name='matched_city_municipality_psgc',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='matchitem',
            name='matched_province_psgc',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
    ]
