# Generated by Django 2.0.7 on 2018-08-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180801_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('interlevel', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('region_code', models.CharField(max_length=256)),
                ('region', models.CharField(max_length=256, null=True)),
                ('province_code', models.CharField(max_length=256)),
                ('province', models.CharField(max_length=256, null=True)),
                ('city_municipality_code', models.CharField(max_length=256)),
                ('city_municipality', models.CharField(max_length=256, null=True)),
                ('barangay_code', models.CharField(max_length=256)),
                ('barangay', models.CharField(max_length=256, null=True)),
                ('original', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='barangay_col',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='city_municipality_col',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='province_col',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
