# Generated by Django 2.1 on 2018-08-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180814_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchitem',
            name='match_type',
            field=models.CharField(choices=[('no_match', 'No Match'), ('near', 'Partial/Near Match'), ('exact', 'Exact Match')], default='no_match', max_length=25),
        ),
    ]
