# Generated by Django 2.1.1 on 2018-09-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_matchitem_match_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchitem',
            name='search_tuple',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
