- pipeline: "Deploy"
  trigger_mode: "ON_EVERY_PUSH"
  ref_name: "master"
  ref_type: "BRANCH"
  target_site_url: "https://linksight.thinkingmachin.es"
  actions:
  - action: "Build React app"
    type: "BUILD"
    working_directory: "/buddy/linksight/app"
    docker_image_name: "library/node"
    docker_image_tag: "8.11-slim"
    execute_commands:
    - "npm install"
    - "npm run build"
    mount_filesystem_path: "/buddy/linksight"
    shell: "BASH"
    trigger_condition: "ALWAYS"
  - action: "Update source"
    type: "RSYNC"
    local_path: "/"
    remote_path: "~/linksight"
    login: "deploy"
    host: "35.240.159.144"
    port: "22"
    env_key: "id_rsa"
    authentication_mode: "ENV_KEY"
    archive: true
    delete_extra_files: true
    compress: true
    deployment_excludes:
    - "/.git/"
    - "/venv/"
    - "/media/"
    - "/app/node_modules/"
    trigger_condition: "ALWAYS"
  - action: "Collect static files and run migrations"
    type: "SSH_COMMAND"
    working_directory: "/deploy/linksight/"
    login: "deploy"
    host: "35.240.159.144"
    port: "22"
    env_key: "id_rsa"
    authentication_mode: "ENV_KEY"
    commands:
    - "venv/bin/python manage.py collectstatic --no-input"
    - "venv/bin/python manage.py migrate"
    run_as_script: true
    shell: "BASH"
    trigger_condition: "ALWAYS"
  - action: "Reload Gunicorn"
    type: "SSH_COMMAND"
    working_directory: "/deploy/linksight/"
    login: "deploy"
    host: "35.240.159.144"
    port: "22"
    env_key: "id_rsa"
    authentication_mode: "ENV_KEY"
    commands:
    - "PID=/deploy/gunicorn.pid"
    - "if [ -f $PID ]; then"
    - "  kill -TERM $(cat $PID)"
    - "fi"
    - "while [ -f $PID ]; do"
    - "  sleep 1"
    - "done"
    - "venv/bin/gunicorn linksight.wsgi -c deploy/gunicorn.py"
    run_as_script: true
    shell: "BASH"
    trigger_condition: "ALWAYS"
  - action: "Send notification to linksight channel"
    type: "SLACK"
    content: "[#${execution.id}] ${execution.pipeline.name} execution by ${execution.to_revision.committer.name}"
    channel: "C7TRAPUR3"
    channel_name: "linksight"
    attachments:
    - "{\"fallback\":\"$BUDDY_PIPELINE_NAME execution #$BUDDY_EXECUTION_ID\",\"color\":\"good\",\"fields\":[{\"title\":\"Successful execution\",\"value\":\"<$BUDDY_EXECUTION_URL|Execution #$BUDDY_EXECUTION_ID $BUDDY_EXECUTION_COMMENT>\",\"short\":true},{\"title\":\"Pipeline\",\"value\":\"<$BUDDY_PIPELINE_URL|$BUDDY_PIPELINE_NAME>\",\"short\":true},{\"title\":\"Branch\",\"value\":\"$BUDDY_EXECUTION_BRANCH\",\"short\":true},{\"title\":\"Project\",\"value\":\"<$BUDDY_PROJECT_URL|$BUDDY_PROJECT_NAME>\",\"short\":true}]}"
    trigger_condition: "ALWAYS"
    integration_id: 25596
