# Build config

images:
- 'gcr.io/$PROJECT_ID/api:$TAG_NAME'
- 'gcr.io/$PROJECT_ID/node:$TAG_NAME'
- 'gcr.io/$PROJECT_ID/nginx:$TAG_NAME'
- 'gcr.io/$PROJECT_ID/imatch:$TAG_NAME'

substitutions:
  _HOST: linksight.thinkingmachin.es

secrets:
- kmsKeyName: projects/linksight-208514/locations/global/keyRings/linksight/cryptoKeys/linksight
  secretEnv:
    SLACK_WEBHOOK: CiQAyqhYTzV2rjhqMlxev10hw99OHfRaBqSExolAiDFsla+dmW4SdwCl9n41cIV/5VSiNrQnqrkGvRAS29uJpy330EusajpZ9QwJz7SzOlqGZKFBWjrWFHriHIyZg7HWSNPFk/RXuK3sOP2gK0tbrT+p2Mpdiw2VE+QNToodDM3WGfv7HPccati0Q/Tvd4I58VpR98YyY7AUBQzLMDEI

steps:

# Pull images for faster builds

- name: 'gcr.io/cloud-builders/docker'
  id: pull-api
  waitFor: ['-']
  entrypoint: bash
  args: ['-c', 'docker pull gcr.io/$PROJECT_ID/api:$TAG_NAME || true']

- name: 'gcr.io/cloud-builders/docker'
  id: pull-node
  waitFor: ['-']
  entrypoint: bash
  args: ['-c', 'docker pull gcr.io/$PROJECT_ID/node:$TAG_NAME || true']

- name: 'gcr.io/cloud-builders/docker'
  id: pull-nginx
  waitFor: ['-']
  entrypoint: bash
  args: ['-c', 'docker pull gcr.io/$PROJECT_ID/nginx:$TAG_NAME || true']

- name: 'gcr.io/cloud-builders/docker'
  id: pull-imatch
  waitFor: ['-']
  entrypoint: bash
  args: ['-c', 'docker pull gcr.io/$PROJECT_ID/imatch:$TAG_NAME || true']

# Setup environment variables

- name: 'gcr.io/cloud-builders/gcloud'
  id: decrypt-env
  waitFor: ['-']
  args:
  - kms
  - decrypt
  - '--ciphertext-file=deploy/secrets/$TAG_NAME/env.enc'
  - --plaintext-file=api/.env
  - --location=global
  - --keyring=linksight
  - --key=linksight

# Build images

- name: 'gcr.io/cloud-builders/docker'
  id: build-api
  waitFor: ['decrypt-env', 'pull-api']
  args:
  - build
  - '-t=gcr.io/$PROJECT_ID/api:$TAG_NAME'
  - '-t=gcr.io/$PROJECT_ID/api:$BUILD_ID'
  - '--cache-from=gcr.io/$PROJECT_ID/api:$TAG_NAME'
  - api

- name: 'gcr.io/cloud-builders/docker'
  id: build-node
  waitFor: ['pull-node']
  args:
  - build
  - -f=deploy/Dockerfile.node
  - --build-arg
  - 'PUBLIC_URL=https://$_HOST'
  - '-t=gcr.io/$PROJECT_ID/node:$TAG_NAME'
  - '-t=gcr.io/$PROJECT_ID/node:$BUILD_ID'
  - '--cache-from=gcr.io/$PROJECT_ID/node:$TAG_NAME'
  - .

- name: 'gcr.io/cloud-builders/docker'
  id: build-nginx
  waitFor: ['pull-nginx', 'build-api', 'build-node']
  args:
  - build
  - -f=deploy/Dockerfile.nginx
  - '-t=gcr.io/$PROJECT_ID/nginx:$TAG_NAME'
  - '-t=gcr.io/$PROJECT_ID/nginx:$BUILD_ID'
  - '--cache-from=gcr.io/$PROJECT_ID/nginx:$TAG_NAME'
  - --build-arg
  - 'NODE_IMAGE=gcr.io/linksight-208514/node:${BUILD_ID}'
  - --build-arg
  - 'TAG_NAME=${TAG_NAME}'
  - .

- name: 'gcr.io/cloud-builders/docker'
  id: build-imatch
  waitFor: ['pull-imatch']
  args:
  - build
  - '-t=gcr.io/$PROJECT_ID/imatch:$TAG_NAME'
  - '-t=gcr.io/$PROJECT_ID/imatch:$BUILD_ID'
  - '--cache-from=gcr.io/$PROJECT_ID/imatch:$TAG_NAME'
  - imatch

# Push images to GCR

- name: 'gcr.io/cloud-builders/docker'
  id: push-api
  waitFor: ['build-api']
  args: ['push', 'gcr.io/$PROJECT_ID/api:$BUILD_ID']

- name: 'gcr.io/cloud-builders/docker'
  id: push-node
  waitFor: ['build-node']
  args: ['push', 'gcr.io/$PROJECT_ID/node:$BUILD_ID']

- name: 'gcr.io/cloud-builders/docker'
  id: push-nginx
  waitFor: ['build-nginx']
  args: ['push', 'gcr.io/$PROJECT_ID/nginx:$BUILD_ID']

- name: 'gcr.io/cloud-builders/docker'
  id: push-imatch
  waitFor: ['build-imatch']
  args: ['push', 'gcr.io/$PROJECT_ID/imatch:$BUILD_ID']

# Decrypt docker certs

- name: 'gcr.io/cloud-builders/gcloud'
  id: decrypt-ca
  waitFor: ['-']
  args:
  - kms
  - decrypt
  - '--ciphertext-file=deploy/secrets/$TAG_NAME/ca.pem.enc'
  - --plaintext-file=ca.pem
  - --location=global
  - --keyring=linksight
  - --key=linksight

- name: 'gcr.io/cloud-builders/gcloud'
  id: decrypt-cert
  waitFor: ['-']
  args:
  - kms
  - decrypt
  - '--ciphertext-file=deploy/secrets/$TAG_NAME/cert.pem.enc'
  - --plaintext-file=cert.pem
  - --location=global
  - --keyring=linksight
  - --key=linksight

- name: 'gcr.io/cloud-builders/gcloud'
  id: decrypt-key
  waitFor: ['-']
  args:
  - kms
  - decrypt
  - '--ciphertext-file=deploy/secrets/$TAG_NAME/key.pem.enc'
  - --plaintext-file=key.pem
  - --location=global
  - --keyring=linksight
  - --key=linksight

# Update services

- name: 'docker/compose:1.22.0'
  id: compose-pull
  waitFor: ['push-imatch', 'push-api', 'push-nginx', 'decrypt-ca', 'decrypt-cert', 'decrypt-key']
  args: ['-p', 'linksight', '-f', 'deploy/docker-compose.yml', 'pull']
  env:
  - 'DOCKER_HOST=$_HOST:2376'
  - DOCKER_TLS_VERIFY=1
  - DOCKER_CERT_PATH=.
  - 'BUILD_ID=$BUILD_ID'

- name: 'docker/compose:1.22.0'
  id: compose-up
  waitFor: ['compose-pull']
  args: ['-p', 'linksight', '-f', 'deploy/docker-compose.yml', 'up', '-d', '--force-recreate']
  env:
  - 'DOCKER_HOST=$_HOST:2376'
  - DOCKER_TLS_VERIFY=1
  - DOCKER_CERT_PATH=.
  - 'BUILD_ID=$BUILD_ID'

# Prune and notify

- name: 'gcr.io/cloud-builders/docker'
  id: docker-prune
  waitFor: ['compose-up']
  args: ['system', 'prune', '-f']

- name: 'gcr.io/cloud-builders/curl'
  id: slack-webhook
  waitFor: ['docker-prune']
  entrypoint: bash
  args:
  - -c
  - >
    curl \
      -X POST \
      -H 'Content-type: application/json' \
      --data '{"text": "Deployed `$BUILD_ID` to `$TAG_NAME`: $_HOST"}' \
      $$SLACK_WEBHOOK
  secretEnv: ['SLACK_WEBHOOK']

