version: "3"
services:

  db:
    image: postgres:9.4
    volumes:
    - db_data:/var/lib/postgresql/data
    network_mode: host
    environment:
      POSTGRES_DB: linksight
    restart: unless-stopped

  redis:
    image: redis:4.0
    command: redis-server --appendonly yes
    volumes:
    - redis_data:/data
    network_mode: host
    restart: unless-stopped

  api:
    image: gcr.io/linksight-208514/python:${BUILD_ID}
    network_mode: host
    depends_on:
    - db
    - redis
    restart: unless-stopped

  worker:
    image: gcr.io/linksight-208514/python:${BUILD_ID}
    command: venv/bin/celery -A linksight worker -P gevent --loglevel INFO
    volumes:
    - imatch_comms:/imatch_vol
    network_mode: host
    depends_on:
    - db
    - redis
    environment:
      IMATCH_SHARED_DIR: /imatch_vol/data/
    restart: unless-stopped

  flower:
    image: gcr.io/linksight-208514/python:${BUILD_ID}
    command: venv/bin/flower -A linksight --conf=linksight/flower.py --address=0.0.0.0 --url_prefix=flower
    network_mode: host
    expose:
    - 5555
    depends_on:
    - db
    - redis
    restart: unless-stopped

  nginx:
    image: gcr.io/linksight-208514/nginx:${BUILD_ID}
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt:ro
    network_mode: host
    depends_on:
    - api
    - flower
    restart: unless-stopped

  imatch:
    image: gcr.io/linksight-208514/imatch:${BUILD_ID}
    volumes:
    - imatch_comms:/imatch_vol
    network_mode: host
    restart: unless-stopped

volumes:
  db_data:
  redis_data:
  imatch_comms:
