FROM nginx:latest
COPY --from=gcr.io/linksight-208514/node /usr/src/app/build/ /var/www
COPY --from=gcr.io/linksight-208514/python /usr/src/app/static/ /var/www
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
