apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: linksight
  labels:
    app: linksight
spec:
  template:
    metadata:
      labels:
        app: linksight
    spec:
      containers:
        - name: "linksight"
          image: "gcr.io/linksight-208514/linksight:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=linksight-208514:asia-southeast1:staging=tcp:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          # [START cloudsql_security_context]
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          # [END cloudsql_security_context]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
        # [END proxy_container]
      # [START volumes]
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
      # [END volumes]

