# Generated by Django 2.1 on 2018-08-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='has_gis_experience',
            field=models.BooleanField(verbose_name='Do you have GIS experience?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='source',
            field=models.TextField(verbose_name='How did you hear about LinkSight?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='usecase',
            field=models.TextField(verbose_name='How can LinkSight help you?'),
        ),
    ]
