# Generated by Django 2.0.5 on 2018-05-09 08:13

from django.db import migrations
from django.contrib.postgres.operations import CryptoExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        CryptoExtension(),
    ]
