# Generated by Django 2.0.6 on 2018-07-01 07:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barangay_col', models.CharField(max_length=256)),
                ('city_municipality_col', models.CharField(max_length=256)),
                ('province_col', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='MatchItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_index', models.IntegerField(editable=False)),
                ('source_barangay', models.CharField(editable=False, max_length=256)),
                ('source_city_municipality', models.CharField(editable=False, max_length=256)),
                ('source_province', models.CharField(editable=False, max_length=256)),
                ('matched_barangay', models.CharField(editable=False, max_length=256)),
                ('matched_barangay_psgc_code', models.CharField(editable=False, max_length=256)),
                ('matched_barangay_score', models.FloatField(editable=False)),
                ('matched_municipality_city', models.CharField(editable=False, max_length=256)),
                ('matched_municipality_city_psgc_code', models.CharField(editable=False, max_length=256)),
                ('matched_municipality_city_score', models.FloatField(editable=False)),
                ('matched_province', models.CharField(editable=False, max_length=256)),
                ('matched_province_psgc_code', models.CharField(editable=False, max_length=256)),
                ('matched_province_score', models.FloatField(editable=False)),
                ('total_score', models.FloatField(editable=False)),
                ('matched', models.BooleanField(editable=False)),
                ('chosen', models.NullBooleanField()),
                ('match', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Match')),
            ],
        ),
    ]
