# Generated by Django 2.0.7 on 2018-07-02 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_match_matchitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.Dataset'),
        ),
        migrations.AlterField(
            model_name='matchitem',
            name='match',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.Match'),
        ),
        migrations.AlterField(
            model_name='matchitem',
            name='matched_barangay',
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='matchitem',
            name='matched_barangay_psgc_code',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='matchitem',
            name='matched_municipality_city',
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='matchitem',
            name='matched_municipality_city_psgc_code',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='matchitem',
            name='matched_province',
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='matchitem',
            name='matched_province_psgc_code',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='matchitem',
            name='source_barangay',
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='matchitem',
            name='source_city_municipality',
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='matchitem',
            name='source_province',
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
    ]
