# Generated by Django 2.0.7 on 2018-07-03 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180702_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchitem',
            options={'ordering': ['dataset_index']},
        ),
        migrations.RenameField(
            model_name='matchitem',
            old_name='matched_municipality_city',
            new_name='matched_city_municipality',
        ),
        migrations.RenameField(
            model_name='matchitem',
            old_name='matched_municipality_city_psgc_code',
            new_name='matched_city_municipality_psgc_code',
        ),
        migrations.RenameField(
            model_name='matchitem',
            old_name='matched_municipality_city_score',
            new_name='matched_city_municipality_score',
        ),
    ]
