# Generated by Django 2.0.7 on 2018-07-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180703_0440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchitem',
            options={'ordering': ['dataset_index', '-total_score']},
        ),
        migrations.AlterField(
            model_name='matchitem',
            name='chosen',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
