# Generated by Django 2.0.7 on 2018-08-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180801_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='barangay_col',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='city_municipality_col',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='province_col',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
