# Generated by Django 2.1 on 2018-08-25 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_matchitem_match_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchitem',
            name='matched',
        ),
    ]
