# Generated by Django 2.1.1 on 2018-09-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_dataset_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchitem',
            name='matched_barangay_psgc',
        ),
        migrations.RemoveField(
            model_name='matchitem',
            name='matched_barangay_score',
        ),
        migrations.RemoveField(
            model_name='matchitem',
            name='matched_city_municipality_psgc',
        ),
        migrations.RemoveField(
            model_name='matchitem',
            name='matched_city_municipality_score',
        ),
        migrations.RemoveField(
            model_name='matchitem',
            name='matched_province_psgc',
        ),
        migrations.RemoveField(
            model_name='matchitem',
            name='matched_province_score',
        ),
        migrations.AddField(
            model_name='matchitem',
            name='code',
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
    ]
