# Generated by Django 2.1.1 on 2018-09-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180912_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchitem',
            name='search_tuple',
            field=models.CharField(default='', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
