# Generated by Django 2.1.1 on 2018-09-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_matchitem_search_tuple'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchitem',
            name='match_time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
