# Generated by Django 2.1.1 on 2018-10-02 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180919_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='barangay_col',
            new_name='source_bgy_col',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='city_municipality_col',
            new_name='source_municity_col',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='province_col',
            new_name='source_prov_col',
        ),
    ]
